security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER, ROLE_PM, ROLE_TL
        ROLE_PM:          ROLE_USER 					#Project Manager
        ROLE_TL:          ROLE_USER                     #Team Leader

    providers:
       main:
         entity: { class: restoo\MainBundle\Entity\User, property: username }

    encoders:
        restoo\MainBundle\Entity\User:    sha512

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: false
            form_login:
                login_path: /login
                check_path: /login-check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
